name: Daily Menu Calendar

on:
  schedule:
    - cron: '0 10 * * *'  # Runs daily at 6 AM ET (10 UTC)
  workflow_dispatch:      # Allows manual run from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y chromium-driver

      - name: Run scraper
        run: python menu_scraper.py

      - name: Commit and push updated calendar
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add menu.ics
          git commit -m "Update menu.ics for $(date +'%Y-%m-%d')" || echo "No changes"
          git push
